INSERT INTO users (
    username,
    password_hash,
    email,
    first_name,
    last_name,
    phone,
    department,
    company_id,
    full_name,
    role,
    status,
    profile_visibility,
    activity_visibility,
    data_sharing,
    require_2fa,
    created_at,
    updated_at
)
VALUES
(
    'fstaff',
    '$2y$12$yxQZHhadli3O38v0i8NzEuEBmI7FbmJH/r6h/qy8kPz9kh4.Gq6Qa',
    'fstaff@atiera.com',
    'Finance',
    'Staff',
    NULL,
    'Finance',
    1,
    'Finance Staff',
    'staff',
    'active',
    'private',
    'private',
    0,
    0,
    NOW(),
    NOW()
),
(
    'fadmin',
    '$2y$12$yxQZHhadli3O38v0i8NzEuEBmI7FbmJH/r6h/qy8kPz9kh4.Gq6Qa',
    'fadmin@atiera.com',
    'Finance',
    'Admin',
    NULL,
    'Finance',
    1,
    'Finance Admin',
    'admin',
    'active',
    'private',
    'private',
    0,
    0,
    NOW(),
    NOW()
)
ON DUPLICATE KEY UPDATE
    password_hash = VALUES(password_hash),
    email = VALUES(email),
    first_name = VALUES(first_name),
    last_name = VALUES(last_name),
    phone = VALUES(phone),
    department = VALUES(department),
    company_id = VALUES(company_id),
    full_name = VALUES(full_name),
    role = VALUES(role),
    status = VALUES(status),
    profile_visibility = VALUES(profile_visibility),
    activity_visibility = VALUES(activity_visibility),
    data_sharing = VALUES(data_sharing),
    require_2fa = VALUES(require_2fa),
    updated_at = VALUES(updated_at);
